manufacturers:
- name: "APC"
  slug: "apc"
  description: "American Power Conversion Corporation, known for power management solutions."
- name: "Apache"
  slug: "apache"
  description: "Open-source software foundation known for the Apache HTTP Server."
- name: "Arista"
  slug: "arista"
  description: ""
- name: "Aruba"
  slug: "aruba"
  description: "Manufacturer of wireless networking equipment."
- name: "Broadcom"
  slug: "broadcom"
  description: "Manufacturer of networking and telecommunications equipment."
- name: "Brocade"
  slug: "brocade"
  description: ""
- name: "Canon"
  slug: "canon"
  description: "Manufacturer of imaging and optical products."
- name: "Cisco"
  slug: "cisco"
  description: "Leading manufacturer of networking hardware and telecommunications equipment."
- name: "Dell"
  slug: "dell"
  description: "Global leader in computer technology and enterprise solutions."
- name: "Extreme"
  slug: "extreme"
  description: ""
- name: "F5"
  slug: "f5"
  description: "Specializes in application delivery networking and load balancing."
- name: "FS"
  slug: "fs"
  description: "Network Equipment Manufacturer and Remanufacturer."
- name: "Fortinet"
  slug: "fortinet"
  description: "Provider of cybersecurity solutions, including firewalls and security appliances."
- name: "Generic"
  slug: "generic"
  description: ""
- name: "Hikvision"
  slug: "hikvision"
  description: "Manufacturer of video surveillance equipment."
- name: "HP"
  slug: "hp"
  description: "Global provider of personal computing and other access devices, imaging and printing products, and related technologies."
- name: "IBM"
  slug: "ibm"
  description: "Multinational technology and consulting company."
- name: "ISC"
  slug: "isc"
  description: "Internet Systems Consortium, known for DHCP and DNS software."
- name: "Juniper"
  slug: "juniper"
  description: ""
- name: "Lenovo"
  slug: "lenovo"
  description: "Manufacturer of personal computers and related technologies."
- name: "Lexmark"
  slug: "lexmark"
  description: "Manufacturer of printers and imaging products."
- name: "Microsoft"
  slug: "microsoft"
  description: "Global technology company known for software, hardware, and cloud services."
- name: "MikroTik"
  slug: "MikroTik"
  description: "Manufacturer of network routers and wireless ISP systems."
- name: "NetApp"
  slug: "netapp"
  description: "Provider of data management and storage solutions."
- name: "Opengear"
  slug: "opengear"
  description: "Company specializing in remote management solutions."
- name: "Oracle"
  slug: "oracle"
  description: "Provider of database software and technology, cloud solutions, and enterprise software."
- name: "Palo Alto"
  slug: "palo-alto"
  description: "Provider of advanced cybersecurity solutions."
- name: "Panduit"
  slug: "panduit"
  description: "Company specializing in network infrastructure solutions."
- name: "QNAP"
  slug: "qnap"
  description: "Manufacturer of network-attached storage (NAS) devices."
- name: "Raspberry Pi"
  slug: "raspberry-pi"
  description: "Manufacturer of single-board computers."
- name: "Siemens"
  slug: "siemens"
  description: "Global technology company focusing on electrification, automation, and digitalization."
- name: "Squid"
  slug: "squid"
  description: "Open-source proxy server software."
- name: "Synology"
  slug: "synology"
  description: "Manufacturer of network-attached storage (NAS) devices."
- name: "TrendNet"
  slug: "trendnet"
  description: "Company specializing in networking hardware."
- name: "Ubiquiti"
  slug: "ubiquiti"
  description: "Company specializing in wireless networking equipment."
- name: "Unknown"
  slug: "unknown"
  description: "Manufacturers not listed above."
- name: "VMware"
  slug: "vmware"
  description: "Leader in virtualization and cloud infrastructure solutions."