platforms:
  - name: "Ubuntu Linux 18.04"
    slug: "ubuntu-linux-18-04"
  - name: "Ubuntu Linux 18.10"
    slug: "ubuntu-linux-18-10"
  - name: "Ubuntu Linux 19.04"
    slug: "ubuntu-linux-19-04"
  - name: "Ubuntu Linux 19.10"
    slug: "ubuntu-linux-19-10"
  - name: "Ubuntu Linux 20.04"
    slug: "ubuntu-linux-20-04"
  - name: "Ubuntu Linux 20.10"
    slug: "ubuntu-linux-20-10"
  - name: "Ubuntu Linux 21.04"
    slug: "ubuntu-linux-21-04"
  - name: "Ubuntu Linux 21.10"
    slug: "ubuntu-linux-21-10"
  - name: "Ubuntu Linux 22.04"
    slug: "ubuntu-linux-22-04"
  - name: "Ubuntu Linux 22.10"
    slug: "ubuntu-linux-22-10"
  - name: "Ubuntu Linux 23.04"
    slug: "ubuntu-linux-23-04"
  - name: "Ubuntu Linux 23.10"
    slug: "ubuntu-linux-23-10"
  - name: "Ubuntu Linux 24.04"
    slug: "ubuntu-linux-24-04"
  - name: "Windows 10"
    manufacturer: "Microsoft"
    slug: "windows-10"
  - name: "Windows 11"
    manufacturer: "Microsoft"
    slug: "windows-11"
  - name: "Windows Server 2016"
    manufacturer: "Microsoft"
    slug: "windows-server-2016"
  - name: "Windows Server 2019"
    manufacturer: "Microsoft"
    slug: "windows-server-2019"
  - name: "Windows Server 2022"
    manufacturer: "Microsoft"
    slug: "windows-server-2022"
  - name: "Windows Server 2025"
    manufacturer: "Microsoft"
    slug: "windows-server-2025"