roles:
  - name: "Access"
    description: "Access network devices providing connectivity to end devices."
    slug: "access"
    color: "9e9e9e"
  - name: "Access Switch"
    description: ""
    slug: "access-switch"
    color: "03a9f4"
  - name: "Application Server"
    description: ""
    slug: "application-server"
    color: "2f6a31"
  - name: "Backup"
    description: "Devices or systems responsible for data backup and recovery."
    slug: "backup"
    color: "9e9e9e"
  - name: "Core"
    description: "Core network devices responsible for routing and switching at the core layer."
    slug: "core"
    color: "9e9e9e"
  - name: "Core Switch"
    description: ""
    slug: "core-switch"
    color: "3f51b5"
  - name: "DHCP Server"
    description: "Servers responsible for dynamic host configuration protocol services."
    slug: "dhcp-server"
    color: "9e9e9e"
  - name: "DNS Server"
    description: "Servers responsible for domain name resolution."
    slug: "dns-server"
    color: "9e9e9e"
  - name: "Database"
    description: "Servers running database management systems."
    slug: "database"
    color: "9e9e9e"
  - name: "Database Server"
    description: ""
    slug: "database-server"
    color: "cddc39"
  - name: "Distribution"
    description: "Distribution network devices aggregating access layer devices and providing uplinks to the core."
    slug: "distribution"
    color: "9e9e9e"
  - name: "Distribution Switch"
    description: ""
    slug: "distribution-switch"
    color: "2196f3"
  - name: "File Server"
    description: "Servers providing file storage and sharing services."
    slug: "file-server"
    color: "9e9e9e"
  - name: "Firewall"
    description: "Devices responsible for network security and traffic filtering."
    slug: "firewall"
    color: "9e9e9e"
  - name: "Hypervisor"
    description: ""
    slug: "hypervisor"
    color: "ff5722"
  - name: "IoT Gateway"
    description: "Devices managing Internet of Things (IoT) devices and data."
    slug: "iot-gateway"
    color: "9e9e9e"
  - name: "Load Balancer"
    description: "Devices responsible for distributing network traffic across multiple servers."
    slug: "load-balancer"
    color: "9e9e9e"
  - name: "Mail Server"
    description: "Servers responsible for sending, receiving, and storing email."
    slug: "mail-server"
    color: "9e9e9e"
  - name: "Monitoring"
    description: "Devices or systems responsible for monitoring network and system performance."
    slug: "monitoring"
    color: "9e9e9e"
  - name: "NAS"
    description: ""
    slug: "nas"
    color: "00bcd4"
  - name: "PDU"
    description: ""
    slug: "pdu"
    color: "607d8b"
  - name: "Patch Panel"
    description: ""
    slug: "patch-panel"
    color: "607d8b"
  - name: "Print Server"
    description: "Servers managing print jobs and printers."
    slug: "print-server"
    color: "9e9e9e"
  - name: "Proxy Server"
    description: "Servers acting as intermediaries for requests from clients seeking resources from other servers."
    slug: "proxy-server"
    color: "9e9e9e"
  - name: "Router"
    description: ""
    slug: "router"
    color: "4caf50"
  - name: "Security Appliance"
    description: "Devices providing various security functions, such as intrusion detection and prevention."
    slug: "security-appliance"
    color: "9e9e9e"
  - name: "Storage"
    description: "Devices responsible for storing data, such as SAN or NAS devices."
    slug: "storage"
    color: "9e9e9e"
  - name: "ToR Switch"
    description: ""
    slug: "tor-switch"
    color: "ff5722"
  - name: "UPS"
    description: ""
    slug: "ups"
    color: "ffeb3b"
  - name: "Unknown"
    description: "Unknown device role."
    slug: "unknown"
    color: "9e9e9e"
  - name: "VPN Gateway"
    description: "Devices providing secure remote access via virtual private networks."
    slug: "vpn-gateway"
    color: "9e9e9e"
  - name: "Virtual Machine"
    description: "Virtualized instances running on hypervisors."
    slug: "virtual-machine"
    color: "9e9e9e"
  - name: "VoIP"
    description: "Devices responsible for voice over IP services."
    slug: "voip"
    color: "9e9e9e"
  - name: "Web Server"
    description: "Servers hosting web applications and services."
    slug: "web-server"
    color: "9e9e9e"
  - name: "Wireless Controller"
    description: "Devices managing wireless access points and wireless network configurations."
    slug: "wireless-controller"
    color: "9e9e9e"