---
manufacturer: Synology
model: RS3617xs
slug: synology-rs3617xs
part_number: RS3617xs
u_height: 2
is_full_depth: true
weight: 14.5
weight_unit: kg
airflow: front-to-rear
comments: ''
front_image: false
rear_image: tfalserue
power-ports:
  - name: PSU 1
    type: iec-60320-c14
interfaces:
  - name: LAN1
    type: 1000base-t
  - name: LAN2
    type: 1000base-t
  - name: LAN3
    type: 1000base-t
  - name: LAN4
    type: 1000base-t
  - name: LAN5
    type: 10gbase-t
  - name: LAN6
    type: 10gbase-t
  - name: Expansion 1
    type: infiniband-ndr
  - name: Expansion 2
    type: infiniband-ndr
console-ports:
  - name: Console
    type: de-9
    mgmt_only: true
